apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/brianwcook/ai-lab-recipes?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ai-lab-recipes
    appstudio.openshift.io/component: nvidia-bootc-builder
    pipelines.appstudio.openshift.io/type: build
  name: nvidia-bootc-builder-on-push
  namespace: brianwcook-tenant
spec:
  params:
  - name: dockerfile
    value: training/nvidia-bootc/Containerfile.builder
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/brianwcook-tenant/ai-lab-recipes/nvidia-bootc-builder:{{revision}}
  - name: revision
    value: '{{revision}}'
  - name: build-args-file
    value: "training/nvidia-bootc/argsfile.conf"
  pipelineRef:
    name: build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'